щось написав, не розумію шо )
VolodymyrBochuliak/JavaScript_LOGOS pull request #14
Opened 2022-09-06 20:02 UTC by VolodymyrBochuliak

не розумію нормально це завдання

2022-09-07 14:40 UTC, VolodymyrBochuliak commented
Advanced HW4 OOP

2022-09-23 21:09 UTC, VolodymyrBochuliak commented
home work #4 oop

2022-10-16 13:30 UTC, MartynLogos requested changes

2022-10-16 13:30 UTC, MartynLogos commented on JS Advanced/home work 4 proto/script.js
> +function CoffeeMakerMachine (name){
Якщо не помиляюсь, то тут мали бути різні класи, і відповідно прописані прототипне наслідування для кожного з них від основного класу.

2022-12-26 12:34 UTC, merged